- name: Enable Redis 7
  ansible.builtin.shell: dnf module disable redis -y; dnf module enable redis:7 -y

- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: latest

- name: Replace config from 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Update protected mode
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'

- name: Start Redis
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: yes

