- name: Setup MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Start MySQL Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: print password
  debug:
    msg: "{{ secrets.ROOT_PASSWORD }}"

- name: Setup MySQL password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ secrets.ROOT_PASSWORD }}




