- name: Enable NodeJS 20
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:20 -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: latest

- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Delete Old App Directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create App Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and Extract App content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /app
    remote_src: yes

- name: Download app dependencies
  community.general.npm:
    path: /app

- name: Setup systemd service file
  ansible.builtin.template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Start catalogue service
  ansible.builtin.systemd_service:
    name: catalogue
    daemon-reload: yes
    state: restarted
    enabled: yes

- name: Copy Mongo Repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongo client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: latest

- name: Load master data
  ansible.builtin.shell: mongosh --host mongo-dev.rdevopsb79.online </app/db/master-data.js



