- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: latest

- name: Include App Pre-requisites
  ansible.builtin.include_tasks:
    file: app-prereq.yml

- name: Download app dependencies
  community.general.shell: mvn clean package; mv target/{{ component }}-1.0.jar {{ component }}.jar
  args:
    chdir: /app

- name: Include Schema
  when: setup_schema is defined and schema_type == "mysql"
  ansible.builtin.include_tasks:
    file: mysql-schema.yml

- name: Include SystemD
  ansible.builtin.include_tasks:
    file: systemd.yml



