- name: Include Schema
  when: setup_schema is defined
  ansible.builtin.include_tasks:
    file: "{{schema_type}}-schema.yml"

- name: Setup systemd service file
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: Start {{ component }} service
  ansible.builtin.systemd_service:
    name: "{{ component }}"
    daemon-reload: yes
    state: restarted
    enabled: yes

